
trigger:
  branches:
    include:
    - refs/heads/*
    - refs/tags/*
jobs:
- job: Build
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: |
      curl -O https://download.clojure.org/install/linux-install-1.10.0.411.sh
      chmod +x linux-install-1.10.0.411.sh
      sudo ./linux-install-1.10.0.411.sh
    displayName: Install Clojure
  - script: clojure -Adev:test
    displayName: Clojure Tests
  - script: npm install
    displayName: Install Node Dependencies
  - script: clojure -Adev:test-cljs
    displayName: ClojureScript Tests
  - script: |
      clojure -A:dev:compile-cljs
      npm run build
    displayName: Package
  - task: CopyFiles@2
    inputs:
      SourceFolder: pkg
      Contents: '**'
      TargetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: mp3-parser
      publishLocation: Container
- job: Test_Windows
  dependsOn: Build
  pool:
    vmImage: win1803
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: current
      downloadType: single
      artifactName: mp3-parser
      downloadPath: $(System.DefaultWorkingDirectory)/pkg
  - script: pkg\mp3-parser-win.exe -h
    displayName: Smoke Test
- job: Test_Mac
  dependsOn: Build
  pool:
    vmImage: macOS-10.13
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: current
      downloadType: single
      artifactName: mp3-parser
      downloadPath: $(System.DefaultWorkingDirectory)/pkg
  - script: |
      chmod +x pkg/mp3-parser-macos
      pkg/mp3-parser-macos -h
    displayName: Smoke Test
- job: Test_Linux
  dependsOn: Build
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: current
      downloadType: single
      artifactName: mp3-parser
      downloadPath: $(System.DefaultWorkingDirectory)/pkg
  - script: |
      chmod +x pkg/mp3-parser-linux
      pkg/mp3-parser-linux -h
    displayName: Smoke Test