
trigger:
  branches:
    include:
    - refs/heads/*
    - refs/tags/*
jobs:
- job: Build
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: |
      curl -O https://download.clojure.org/install/linux-install-1.10.0.411.sh
      chmod +x linux-install-1.10.0.411.sh
      sudo ./linux-install-1.10.0.411.sh
    displayName: Install Clojure
  - script: clojure -Adev:test
    displayName: Clojure Tests
  - script: npm install
    displayName: Install Node Dependencies
  - script: clojure -Adev:test-cljs
    displayName: ClojureScript Tests